### ISSUE TITLE
glesys-dns-01-hook.sh has some issues

### ISSUE THREAD

**Issue by marcusmansson** [glesys/api-docs#32]
It does not work with wildcard certificates.
It puts the API user and access key on the command line.
It breaks with recent versions of dehydrate.

I've fixed those issues, and more, feel free to copy!
https://gitlab.com/marcusmansson/glesys-dns01

**Comment by kiranos** [comment]
@marcusmansson Hi nice! sorry for the late reply, we've tested your version and it would be great if we were allowed to replace our script with this in our API examples?

**Comment by marcusmansson** [comment]
@kiranos Thanks! Feel free to use it!
